### ISSUE TITLE
与其他 ui 组件共用冲突问题

### ISSUE THREAD

**Issue by bbcef** [zebra-ui/zebra-ui#42]
### 清晰简洁的描述你的需求

与 uvui 组件库共用时，bem 方法会被uvui优先使用  如图： 
![微信图片_20240521105920](https://github.com/zebra-ui/zebra-ui/assets/30925099/ef671d3b-4051-4386-bf75-44901904d34f)
![微信图片_20240521110010](https://github.com/zebra-ui/zebra-ui/assets/30925099/08ff2419-b58e-465e-a20d-b82693f8b21e)

### 此需求你建议怎样实现

对使用的内置方法做唯一区别，如 加前缀（zBem等）。

**Comment by Ru1ers** [comment]
暂不考虑解决与其他组件库共用时出现的问题
